# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.6.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.6.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vargyas/Work/ALICE/IAA/corr

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vargyas/Work/ALICE/IAA/corr

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vargyas/Work/ALICE/IAA/corr/CMakeFiles /Users/vargyas/Work/ALICE/IAA/corr/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vargyas/Work/ALICE/IAA/corr/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named process

# Build rule for target.
process: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 process
.PHONY : process

# fast build rule for target.
process/fast:
	$(MAKE) -f CMakeFiles/process.dir/build.make CMakeFiles/process.dir/build
.PHONY : process/fast

#=============================================================================
# Target rules for targets named IAA

# Build rule for target.
IAA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IAA
.PHONY : IAA

# fast build rule for target.
IAA/fast:
	$(MAKE) -f CMakeFiles/IAA.dir/build.make CMakeFiles/IAA.dir/build
.PHONY : IAA/fast

#=============================================================================
# Target rules for targets named G__IAA

# Build rule for target.
G__IAA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 G__IAA
.PHONY : G__IAA

# fast build rule for target.
G__IAA/fast:
	$(MAKE) -f CMakeFiles/G__IAA.dir/build.make CMakeFiles/G__IAA.dir/build
.PHONY : G__IAA/fast

G__IAA.o: G__IAA.cxx.o

.PHONY : G__IAA.o

# target to build an object file
G__IAA.cxx.o:
	$(MAKE) -f CMakeFiles/IAA.dir/build.make CMakeFiles/IAA.dir/G__IAA.cxx.o
.PHONY : G__IAA.cxx.o

G__IAA.i: G__IAA.cxx.i

.PHONY : G__IAA.i

# target to preprocess a source file
G__IAA.cxx.i:
	$(MAKE) -f CMakeFiles/IAA.dir/build.make CMakeFiles/IAA.dir/G__IAA.cxx.i
.PHONY : G__IAA.cxx.i

G__IAA.s: G__IAA.cxx.s

.PHONY : G__IAA.s

# target to generate assembly for a file
G__IAA.cxx.s:
	$(MAKE) -f CMakeFiles/IAA.dir/build.make CMakeFiles/IAA.dir/G__IAA.cxx.s
.PHONY : G__IAA.cxx.s

processDraw.o: processDraw.cxx.o

.PHONY : processDraw.o

# target to build an object file
processDraw.cxx.o:
	$(MAKE) -f CMakeFiles/process.dir/build.make CMakeFiles/process.dir/processDraw.cxx.o
.PHONY : processDraw.cxx.o

processDraw.i: processDraw.cxx.i

.PHONY : processDraw.i

# target to preprocess a source file
processDraw.cxx.i:
	$(MAKE) -f CMakeFiles/process.dir/build.make CMakeFiles/process.dir/processDraw.cxx.i
.PHONY : processDraw.cxx.i

processDraw.s: processDraw.cxx.s

.PHONY : processDraw.s

# target to generate assembly for a file
processDraw.cxx.s:
	$(MAKE) -f CMakeFiles/process.dir/build.make CMakeFiles/process.dir/processDraw.cxx.s
.PHONY : processDraw.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... process"
	@echo "... IAA"
	@echo "... G__IAA"
	@echo "... G__IAA.o"
	@echo "... G__IAA.i"
	@echo "... G__IAA.s"
	@echo "... processDraw.o"
	@echo "... processDraw.i"
	@echo "... processDraw.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

